<x-master-layout>
    @section('content')
        @if(Auth::check())
            @include('dashboard')
        @else
            @include('auth.login')
        @endif
    @endsection
</x-master-layout>